---
title: 'Video 15:'
author: "Josh Erickson"
date: "7/13/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
theme_set(theme_bw())
trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)
library(wesanderson)
```

Let's bootstrap some data for [claremont run project from #tidytuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-06-30/readme.md)

Highlights= {naniar} with gg_miss_upset() is a really nice eda tool! 

## Explore Data

```{r}
# Get the Data

tuesdata <- tidytuesdayR::tt_load('2020-06-30')


character_visualization <- tuesdata$character_visualization
xmen_bechdel <- tuesdata$xmen_bechdel
locations <- tuesdata$locations

```

```{r}
character_visualization %>% distinct(character)
character_visualization %>% filter(depicted < 1)
locations %>% count(location, sort = T) %>% filter(n > 10)

x_mansion <- locations %>% group_by(issue) %>% summarise(mansion = 'X-Mansion' %in% location) 

```

```{r}
xmen_bechdel %>% count(pass_bechdel)
```

```{r}
per_issue <- character_visualization %>% 
  group_by(issue) %>% 
  summarise(across(speech:depicted, sum)) %>% 
  ungroup()
  

locations_joined <- per_issue %>% 
  inner_join(x_mansion)

locations_joined %>% 
  mutate(mansion = if_else(mansion, 'X-Mansion', 'No Mansion')) %>% 
  pivot_longer(speech:depicted, names_to = 'visualization') %>% 
  ggplot(aes(mansion, value, fill = visualization)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', 
               show.legend = F) +
  scale_fill_manual(values = wes_palette('Darjeeling2')) +
  facet_wrap(~visualization, scales = 'free_y')
```



```{r}
set.seed(244)

boots <- bootstraps(locations_joined, times = 1000, apparent = TRUE)

boot_models <- boots %>% 
  mutate(model = map(splits, ~glm(mansion ~ speech + thought + narrative + depicted, family = 'binomial', data = analysis(.))),
         coef_info = map(model, tidy))

boot_coefs <- boot_models %>% 
  unnest(coef_info)

int_pctl(boot_models, coef_info)
```

```{r}
boot_coefs %>% 
  filter(term != '(Intercept)') %>% 
  ggplot(aes(estimate, fill = term)) + 
  geom_histogram(alpha = 0.8, bins = 25, show.legend = F) +
  geom_vline(xintercept = 0, color = 'grey50', lty=2, alpha = 0.6, size = 1.5)+
  facet_wrap(~term, scales = 'free')
```




```{r}

locations_joined <- per_issue %>% 
  inner_join(xmen_bechdel) %>% 
  mutate(pass_bechdel = if_else(pass_bechdel == 'yes', TRUE, FALSE)) 



locations_joined %>% 
  mutate(pass_bechdel = if_else(pass_bechdel, 'Passes Bechdel', 'No Bechdel')) %>% 
  pivot_longer(speech:depicted, names_to = 'visualization') %>% 
  ggplot(aes(pass_bechdel, value, fill = visualization)) +
  geom_dotplot(binaxis = 'y', stackdir = 'center', 
               show.legend = F) +
  scale_fill_manual(values = wes_palette('Darjeeling2')) +
  facet_wrap(~visualization, scales = 'free_y')

set.seed(244)

boots <- bootstraps(locations_joined, times = 1000, apparent = TRUE)

boot_models <- boots %>% 
  mutate(model = map(splits, ~glm(pass_bechdel ~ speech + thought + narrative + depicted, family = 'binomial', data = analysis(.))),
         coef_info = map(model, tidy))

boot_coefs <- boot_models %>% 
  unnest(coef_info)

int_pctl(boot_models, coef_info)


boot_coefs %>% 
  filter(term != '(Intercept)') %>% 
  ggplot(aes(estimate, fill = term)) + 
  geom_histogram(alpha = 0.8, bins = 25, show.legend = F) +
  geom_vline(xintercept = 0, color = 'grey50', lty=2, alpha = 0.6, size = 1.5)+
  facet_wrap(~term, scales = 'free')
```
































