---
title: 'video 19: crop yields'
author: "Josh Erickson"
date: "7/20/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
theme_set(theme_bw())
trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)
library(wesanderson)
```

Let's build a model from some data for [crop yields #tidytuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-09-1/readme.md)

Highlights= just found out you can use nest(data = c(year, yield)) instead of grouping and then nesting. map a ~lm() and then tidy is so so nice. 

## Explore Data

```{r}
# Get the Data

tuesdata <- tidytuesdayR::tt_load('2020-09-1')


key_crop_yields <- tuesdata$key_crop_yields
land_use <- tuesdata$land_use_vs_yield_change_in_cereal_production
key_crop_yields %>% view()
avatar_raw %>% count(character, book, sort = T)
key_crop_yields %>% distinct(Entity)
```

## Explore 


```{r}
top_countries <- land_use %>% 
  janitor::clean_names() %>% 
  filter(!is.na(code),
         entity != 'World') %>% 
  group_by(entity) %>% 
  filter(year == max(year)) %>% 
  ungroup() %>% 
  slice_max(total_population_gapminder , n = 30) %>% 
  pull(entity)
```


```{r}
tidy_yields <- key_crop_yields %>% 
  janitor::clean_names() %>% 
  pivot_longer(wheat_tonnes_per_hectare:bananas_tonnes_per_hectare,
               names_to = 'crop', values_to = 'yield') %>% 
  mutate(crop = str_remove(crop, '_tonnes_per_hectare')) %>% 
  filter(crop %in% c('wheat', 'rice', 'maize', 'barley'),
         entity %in% 'United States',
         !is.na(yield))
```


```{r}
ty <- tidy_yields %>% mutate(year2 = year) %>% 
  ggplot() + 
  geom_line(aes(year2, yield, color = crop, frame = year)) 

fig <- ggplotly(ty)
fig
```


```{r}
tidy_lm <- tidy_yields %>% 
  nest(yields = c(year, yield)) %>% 
  mutate(model = map(yields, ~lm(yield~year, data = .x)))

slopes <- tidy_lm %>% 
  mutate(coefs = map(model, tidy)) %>% 
  unnest(coefs) %>% filter(term == 'year') %>% 
  mutate(p.value = p.adjust(p.value,method = 'BH'))

slopes

```


## Explore results

```{r}
slopes %>% 
  ggplot(aes(estimate, p.value, label = entity)) +
  geom_point(alpha = 0.8, size = 2.5, aes(color = entity),show.legend = F) +
  geom_text(check_overlap = T) +
  facet_wrap(~crop) + 
  scale_y_log10()
```

























