---
title: 'Video 27:'
author: "Josh Erickson"
date: "7/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
theme_set(theme_bw())

trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)

library(wesanderson)
```

Let's build a model from some data for [student debt #tidytuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2021-02-23/readme.md)

Highlights=  

## Explore Data

```{r}
# Get the Data

tuesdata <- tidytuesdayR::tt_load('2021-02-23')


employed <- tuesdata$employed

employed %>% skim()

employed_tidy <- employed %>% 
  filter(!is.na(employ_n)) %>% 
  group_by(occupation = paste(industry, minor_occupation),
           race_gender) %>% 
  summarise(n = mean(employ_n)) %>% 
  ungroup()


employment_demo <- employed_tidy %>% 
  filter(race_gender %in% c("Women", "Black or African American", "Asian")) %>%  pivot_wider(names_from = race_gender, values_from = n, values_fill = 0) %>% 
  janitor::clean_names() %>% 
  left_join(employed_tidy %>% 
              filter(race_gender == "TOTAL") %>% 
              select(-race_gender) %>% 
            rename(total = 'n')) %>% 
  filter(total > 1e4) %>% 
  mutate(across(c(asian, black_or_african_american, women), ~ ./total),
         total = log(total),
         across(is.numeric, ~as.numeric(scale(.))))


```



## implement k-means

```{r}
employment_clust <- kmeans(select(employment_demo, -occupation), centers = 3)

summary(employment_clust)

library(broom)

tidy(employment_clust)

augment(employment_clust, employment_demo) %>% 
  ggplot(aes(total, black_or_african_american, color = .cluster)) +
  geom_point()

```

```{r}

kclusts <- 
  tibble(k = 1:9) %>% 
  mutate(
    kclust = map(k, ~kmeans(select(employment_demo, -occupation), .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, employment_demo)
  )


kclusts %>% 
  unnest(glanced) %>% 
  ggplot(aes(k, tot.withinss)) +
  geom_line() + geom_point()

employment_clust <- kmeans(select(employment_demo, -occupation), centers = 5)


p <- augment(employment_clust, employment_demo) %>% 
  ggplot(aes(total, black_or_african_american, color = .cluster, 
             name = occupation)) +
  geom_point()


plotly::ggplotly(p)

```
















