---
title: 'Video 24:'
author: "Josh Erickson"
date: "7/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
theme_set(theme_bw())

trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)

library(wesanderson)
```

Let's build a model from some data for [student debt #tidytuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-11-03/readme.md)

Highlights=  

## Explore Data

```{r}
# Get the Data

tuesdata <- tidytuesdayR::tt_load('2021-02-09')


student_debt <- tuesdata$student_debt

student_debt %>% view()

```

## Explore 

```{r}

student_debt %>% 
  ggplot(aes(year, loan_debt_pct, color = race)) + 
  geom_point() + 
  geom_smooth(se=F, method = 'lm')
```


```{r}

lm_spec <- linear_reg() %>% set_engine('lm')

lm_fit <- lm_spec %>% 
  fit(loan_debt_pct ~ year * race, data = student_debt)

tidy(lm_fit)
```

Explore model results

```{r}
new_points <- crossing(race = c("Black", "Hispanic", "White"),
                       year = 1990:2020)
augment(lm_fit, new_data = new_points) %>% 
   ggplot(aes(year, .pred, color = race)) + 
  geom_line(alpha = 0.7) + 
  geom_smooth(se=F, method = 'lm')
```












