---
title: 'Video 26: superbowl commercials'
author: "Josh Erickson"
date: "7/27/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
theme_set(theme_bw())

trace(grDevices::png, quote({
  if (missing(type) && missing(antialias)) {
    type <- "cairo-png"
    antialias <- "subpixel"
  }
}), print = FALSE)

library(wesanderson)
```

Let's build a model from some data for [superbowl commercials #tidytuesday data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-03-02/readme.md)

Highlights=  

## Explore Data

```{r}
# Get the Data

tuesdata <- tidytuesdayR::tt_load('2021-03-02')


youtube <- tuesdata$youtube



```

## Explore 


```{r}
youtube %>% 
  select(year, funny:use_sex) %>% 
  pivot_longer(funny:use_sex) %>% 
  group_by(year, name) %>% 
  summarise(prop = mean(value)) %>% 
  ungroup() %>% 
  ggplot(aes(year, prop, color = name)) + 
  geom_line() + 
  facet_wrap(vars(name))
```


## fit a simple model

```{r}
simple_mod <- lm(year ~ funny + show_product_quickly + patriotic + celebrity + danger + animals + use_sex, data = youtube)

summary(simple_mod)


```

```{r}
library(rsample)

bootstraps(youtube, 1e3)

```



```{r}
set.seed(1234)

youtube_intervals <- reg_intervals(formula = year ~ funny + show_product_quickly + patriotic + celebrity + danger + animals + use_sex, 
              data = youtube,
                type = 'percentile',
              keep_reps = T)
```



```{r}
youtube_intervals %>% 
  mutate(term = str_remove(term, "TRUE"),
         term = fct_reorder(term, .estimate)) %>% 
  ggplot(aes(.estimate, term)) + 
  geom_errorbar(aes(xmin = .lower, xmax = .upper)) +
  geom_point()
```





















